### ISSUE TITLE
invalid json?

### ISSUE THREAD

**Issue by brainskittles** [hobbydevs/InstabotJS#2]
every time the bot tries to like a post, i get this error:

JSON ERROR { FetchError: invalid json response body at https://www.instagram.com/p/B0x4CTKhKST/?__a=1 reason: Unexpected token < in JSON at position 0
    at /home/ebukaamadiobi/InstabotJS/node_modules/node-fetch/lib/index.js:239:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://www.instagram.com/p/B0x4CTKhKST/?__a=1 reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }

what could the problem be? the follow mode is working fine.

**Comment by AsiaGenius** [comment]
some here

**Comment by brainskittles** [comment]
Are you any closer to solving the problem? I wanna get this working ASAP.

**Comment by urboithellama** [comment]
Having this issue as well.
